package launch

import (
	"context"
	"crypto/rand"
	"encoding/base64"
	"fmt"
	"net/url"
	"strconv"
	"strings"

	"github.com/chadsmith12/berth/pkg/coolify"
)

// Client is the slice of the Coolify API launch needs. *coolify.Client
// satisfies it; tests substitute a fake.
type Client interface {
	Projects(ctx context.Context) ([]coolify.Project, error)
	CreateProject(ctx context.Context, name string) (string, error)
	Project(ctx context.Context, uuid string) (coolify.ProjectDetail, error)
	CreateEnvironment(ctx context.Context, projectUUID, name string) (string, error)
	Servers(ctx context.Context) ([]coolify.Server, error)
	PrivateKeys(ctx context.Context) ([]coolify.PrivateKey, error)
	CreatePrivateKey(ctx context.Context, name, privateKeyPEM string) (string, error)
	Databases(ctx context.Context) ([]coolify.Database, error)
	Database(ctx context.Context, uuid string) (coolify.DatabaseDetail, error)
	CreateApplication(ctx context.Context, body coolify.CreateApplicationBody) (string, error)
	EnvVars(ctx context.Context, appUUID string) ([]coolify.EnvVar, error)
	SetEnvVar(ctx context.Context, appUUID, key, value string) error
}

// Inputs are the resolved decisions for one launch. The frontend (CLI
// prompts, GUI forms) fills them; Execute then runs the idempotent
// find-or-create steps against Coolify. Nothing here prompts.
type Inputs struct {
	ProjectName     string
	EnvironmentName string
	ServerUUID      string
	GitRepository   string // normalized git@host:port/path form
	Branch          string
	PrivateKeyUUID  string // existing key; empty means generate one named NewKeyName
	NewKeyName      string
	Domain          string // host[:port]; the port is derived from AppPort
	AppPort         int
	DatabaseUUID    string // "" = no database
	DatabaseName    string // the logical database to use; "" = the resource's postgres_db
	RedisUUID       string // "" = no redis (required by horizon stacks)
	EnvFileName     string // docker-compose.<env>.yml, as Coolify should reference it
	BaseDir         string // the app's base directory relative to the repo root ("" = repo root). Coolify combines it with the compose file location.
}

// Step records what one find-or-create step did.
type Step struct {
	Name    string
	UUID    string
	Created bool
}

type Result struct {
	Project     Step
	Environment Step
	Server      Step
	DeployKey   Step
	Application Step
	EnvVars     []string
	// Notices are things the user must act on (e.g. a chosen database that
	// does not exist in the postgres resource yet).
	Notices []string
}

// Execute runs the launch steps in order. Every step except application
// creation is find-or-create, so re-running after a partial failure resumes.
// If a crash lands between application creation and recording its uuid, the
// recovery is adopt mode: berth launch --uuid <uuid>.
func Execute(ctx context.Context, client Client, in Inputs) (Result, error) {
	var res Result

	if in.ProjectName == "" || in.EnvironmentName == "" || in.ServerUUID == "" ||
		in.GitRepository == "" || in.Branch == "" || in.AppPort <= 0 || in.Domain == "" {
		return res, fmt.Errorf("launch inputs are incomplete — project, environment, server, repository, branch, port and domain are all required")
	}

	project, err := resolveProject(ctx, client, in.ProjectName)
	if err != nil {
		return res, err
	}
	res.Project = project

	env, err := resolveEnvironment(ctx, client, project.UUID, in.EnvironmentName)
	if err != nil {
		return res, err
	}
	res.Environment = env

	server, err := resolveServer(ctx, client, in.ServerUUID)
	if err != nil {
		return res, err
	}
	res.Server = server

	key, err := ResolveDeployKey(ctx, client, in.PrivateKeyUUID, in.NewKeyName)
	if err != nil {
		return res, err
	}
	res.DeployKey = Step{Name: key.Name, UUID: key.UUID, Created: key.Created}

	dbVars, notices, err := databaseEnvVars(ctx, client, in)
	if err != nil {
		return res, err
	}
	res.Notices = notices

	domain, err := domainWithPort(in.Domain, in.AppPort)
	if err != nil {
		return res, err
	}

	appName := fmt.Sprintf("%s-%s", in.ProjectName, in.EnvironmentName)
	appUUID, err := client.CreateApplication(ctx, coolify.CreateApplicationBody{
		ProjectUUID:            project.UUID,
		EnvironmentName:        in.EnvironmentName,
		ServerUUID:             server.UUID,
		GitRepository:          in.GitRepository,
		GitBranch:              in.Branch,
		PrivateKeyUUID:         key.UUID,
		BuildPack:              "dockercompose",
		BaseDirectory:          baseDirectory(in.BaseDir),
		DockerComposeLocation:  "/" + in.EnvFileName,
		ConnectToDockerNetwork: true,
		AutogenerateDomain:     false,
		Name:                   appName,
		DockerComposeDomains: map[string]coolify.ComposeDomainBody{
			"app": {Domain: domain, Name: "app"},
		},
	})
	if err != nil {
		return res, err
	}
	res.Application = Step{Name: appName, UUID: appUUID, Created: true}

	keys, err := setEnvVars(ctx, client, appUUID, dbVars)
	if err != nil {
		return res, err
	}
	res.EnvVars = keys

	return res, nil
}

func resolveProject(ctx context.Context, client Client, name string) (Step, error) {
	projects, err := client.Projects(ctx)
	if err != nil {
		return Step{}, err
	}
	var matches []coolify.Project
	for _, p := range projects {
		if p.Name == name {
			matches = append(matches, p)
		}
	}
	switch len(matches) {
	case 0:
		uuid, err := client.CreateProject(ctx, name)
		if err != nil {
			return Step{}, err
		}
		return Step{Name: name, UUID: uuid, Created: true}, nil
	case 1:
		return Step{Name: name, UUID: matches[0].UUID}, nil
	default:
		return Step{}, fmt.Errorf("%d projects named %q — rename one in Coolify before launching", len(matches), name)
	}
}

func resolveEnvironment(ctx context.Context, client Client, projectUUID, name string) (Step, error) {
	detail, err := client.Project(ctx, projectUUID)
	if err != nil {
		return Step{}, err
	}
	var matches []coolify.Environment
	for _, e := range detail.Environments {
		if e.Name == name {
			matches = append(matches, e)
		}
	}
	switch len(matches) {
	case 0:
		uuid, err := client.CreateEnvironment(ctx, projectUUID, name)
		if err != nil {
			return Step{}, err
		}
		return Step{Name: name, UUID: uuid, Created: true}, nil
	case 1:
		return Step{Name: name, UUID: matches[0].UUID}, nil
	default:
		return Step{}, fmt.Errorf("%d environments named %q — rename one in Coolify before launching", len(matches), name)
	}
}

func resolveServer(ctx context.Context, client Client, uuid string) (Step, error) {
	servers, err := client.Servers(ctx)
	if err != nil {
		return Step{}, err
	}
	for _, s := range servers {
		if s.UUID == uuid {
			return Step{Name: s.Name, UUID: s.UUID}, nil
		}
	}
	names := make([]string, 0, len(servers))
	for _, s := range servers {
		names = append(names, fmt.Sprintf("%s (%s)", s.Name, s.UUID))
	}
	return Step{}, fmt.Errorf("no server %q — available: %s", uuid, strings.Join(names, ", "))
}

// DeployKeyChoice is the outcome of picking or creating a deploy key.
type DeployKeyChoice struct {
	UUID      string
	Name      string
	Created   bool
	PublicKey string
}

// LookupDeployKey validates an existing key uuid.
func LookupDeployKey(ctx context.Context, client Client, uuid string) (DeployKeyChoice, error) {
	keys, err := client.PrivateKeys(ctx)
	if err != nil {
		return DeployKeyChoice{}, err
	}
	for _, k := range keys {
		if k.UUID == uuid {
			return DeployKeyChoice{UUID: k.UUID, Name: k.Name}, nil
		}
	}
	return DeployKeyChoice{}, fmt.Errorf("no deploy key %q — available: %s", uuid, keyNames(keys))
}

// CreateDeployKey generates and stores a new keypair. The public half must be
// pasted into the git host before anything can deploy — that is the one step
// berth cannot do for you.
func CreateDeployKey(ctx context.Context, client Client, name string) (DeployKeyChoice, error) {
	if name == "" {
		name = "berth-deploy-key"
	}
	pair, err := GenerateKeyPair(name)
	if err != nil {
		return DeployKeyChoice{}, err
	}
	uuid, err := client.CreatePrivateKey(ctx, name, pair.PrivateKey)
	if err != nil {
		return DeployKeyChoice{}, err
	}
	return DeployKeyChoice{UUID: uuid, Name: name, Created: true, PublicKey: pair.PublicKey}, nil
}

// ResolveDeployKey validates an existing key uuid or generates and stores a
// new keypair.
func ResolveDeployKey(ctx context.Context, client Client, uuidFlag, newName string) (DeployKeyChoice, error) {
	if uuidFlag != "" {
		return LookupDeployKey(ctx, client, uuidFlag)
	}
	return CreateDeployKey(ctx, client, newName)
}

func keyNames(keys []coolify.PrivateKey) string {
	names := make([]string, 0, len(keys))
	for _, k := range keys {
		names = append(names, fmt.Sprintf("%s (%s)", k.Name, k.UUID))
	}
	return strings.Join(names, ", ")
}

// domainWithPort appends the compose port to a portless domain.
//
// The scheme is preserved: Only http and https are accepted, so a bare
// host (no scheme) and a non-web scheme are both normalized or refused
func domainWithPort(domain string, port int) (string, error) {
	raw := strings.TrimSpace(domain)
	if raw == "" {
		return "", fmt.Errorf("missing domain")
	}
	if !strings.Contains(raw, "://") {
		raw = "http://" + raw
	}
	u, err := url.Parse(raw)
	if err != nil || u.Host == "" {
		return "", fmt.Errorf("invalid domain %q", domain)
	}
	switch u.Scheme {
	case "http", "https":
	default:
		return "", fmt.Errorf("domain %q must use http:// or https://, not %q — https enables TLS, http does not", domain, u.Scheme)
	}
	if have := u.Port(); have != "" {
		n, err := strconv.Atoi(have)
		if err != nil || n != port {
			return "", fmt.Errorf("domain %s uses port %s, but docker-compose exposes %d — fix one of them", domain, have, port)
		}
		return raw, nil
	}
	u.Host = fmt.Sprintf("%s:%d", u.Hostname(), port)
	return u.String(), nil
}

// baseDirectory maps an app base directory to Coolify's /-prefixed form.
// Coolify requires a leading slash; an empty base dir (app at the repo root)
// means "/".
func baseDirectory(baseDir string) string {
	baseDir = strings.TrimSpace(baseDir)
	baseDir = strings.Trim(baseDir, "/")
	if baseDir == "" {
		return "/"
	}
	return "/" + baseDir
}

// databaseEnvVars turns the selected database and redis resources into the
// env vars the compose stack consumes. Hosts are the resource uuids — that
// is how Coolify names the containers on the shared network. Passwords only
// come back for tokens with read:sensitive; anything else is a loud failure,
// never an empty value written to Coolify.
func databaseEnvVars(ctx context.Context, client Client, in Inputs) (map[string]string, []string, error) {
	vars := map[string]string{}
	var notices []string
	if in.DatabaseUUID != "" {
		db, err := client.Database(ctx, in.DatabaseUUID)
		if err != nil {
			return nil, nil, err
		}
		if !strings.Contains(db.Type, "postgres") {
			return nil, nil, fmt.Errorf("database %q is %s, not postgres", db.Name, db.Type)
		}
		if db.PostgresPassword == "" || db.PostgresDB == "" || db.PostgresUser == "" {
			return nil, nil, fmt.Errorf("database %q returned empty credentials — the token lacks the read:sensitive ability; create a token with it in Coolify (Keys & Tokens) and run berth auth login", db.Name)
		}
		name := db.PostgresDB
		if in.DatabaseName != "" {
			name = in.DatabaseName
		}
		if name != db.PostgresDB {
			notices = append(notices, fmt.Sprintf(
				"database %q does not exist in %q yet — create it on that postgres (e.g. CREATE DATABASE %s) before deploying",
				name, db.Name, name))
		}
		vars["DB_HOST"] = db.UUID
		vars["DB_PORT"] = "5432"
		vars["DB_DATABASE"] = name
		vars["DB_USERNAME"] = db.PostgresUser
		vars["DB_PASSWORD"] = db.PostgresPassword
	}
	if in.RedisUUID != "" {
		db, err := client.Database(ctx, in.RedisUUID)
		if err != nil {
			return nil, nil, err
		}
		if !strings.Contains(db.Type, "redis") {
			return nil, nil, fmt.Errorf("resource %q is %s, not redis", db.Name, db.Type)
		}
		vars["REDIS_HOST"] = db.UUID
		vars["REDIS_PORT"] = "6379"
		if db.RedisPassword != "" {
			vars["REDIS_PASSWORD"] = db.RedisPassword
		}
	}
	return vars, notices, nil
}

// setEnvVars writes the compose env vars plus APP_KEY, which is generated
// once: regenerating it would make every encrypted column unreadable.
func setEnvVars(ctx context.Context, client Client, appUUID string, vars map[string]string) ([]string, error) {
	existing, err := client.EnvVars(ctx, appUUID)
	if err != nil {
		return nil, err
	}
	present := map[string]bool{}
	for _, e := range existing {
		present[e.Key] = true
	}

	set := map[string]string{}
	for k, v := range vars {
		set[k] = v
	}
	if !present["APP_KEY"] {
		key, err := generateAppKey()
		if err != nil {
			return nil, err
		}
		set["APP_KEY"] = key
	}

	names := make([]string, 0, len(set))
	for k, v := range set {
		if err := client.SetEnvVar(ctx, appUUID, k, v); err != nil {
			return nil, fmt.Errorf("set %s: %w", k, err)
		}
		names = append(names, k)
	}
	return names, nil
}

func generateAppKey() (string, error) {
	b := make([]byte, 32)
	if _, err := rand.Read(b); err != nil {
		return "", fmt.Errorf("generate APP_KEY: %w", err)
	}
	return "base64:" + base64.StdEncoding.EncodeToString(b), nil
}
